Create /var/run/minidlna and put the PID file in it (closes: #617722, #613853)
The directory /var/run/minidlna is made writable by the minidlna user,
so that the minidlna daemon can create its PID file. Thanks to Michael
Schutte and Thomas Viehweger for reporting the issue and proposing a
patch.

diff --git a/debian/minidlna.postrm b/debian/minidlna.postrm
--- a/debian/minidlna.postrm
+++ b/debian/minidlna.postrm
@@ -7,12 +7,13 @@ USER=minidlna
 GROUP=${USER}
 HOME=`getent passwd ${USER} | awk -F: '{ print $6 }'`
 CONFIG=/etc/minidlna.conf
+PIDDIR=/var/run/minidlna
 
 # Based on the mediatomb debian package.
 
 case "$1" in
     remove)
-        rm -f /var/run/minidlna.pid
+        rm -rf ${PIDDIR}
         ;;
 
     purge)
@@ -23,13 +24,19 @@ case "$1" in
             rm -f  "${dir}/files.db"
             [ -d "${dir}" ] && rmdir --ignore-fail-on-non-empty "${dir}"
         done
-        rm -f /var/run/minidlna.pid /var/log/minidlna.log ${CONFIG}
+        rm -f /var/log/minidlna.log ${CONFIG}
 
-        dpkg-statoverride --quiet --remove ${CONFIG}
-        dpkg-statoverride --quiet --remove /var/lib/minidlna
+        dpkg-statoverride --quiet --remove ${CONFIG} || true
+        dpkg-statoverride --quiet --remove /var/lib/minidlna || true
 
-        ( deluser --quiet --system ${USER}   && echo "Removing user \`${USER}'." )   || true
-        ( delgroup --quiet --system ${GROUP} && echo "Removing group \`${GROUP}'." ) || true
+        if getent passwd ${USER} >/dev/null; then
+            echo -n "Removing user '${USER}'..."
+            deluser --quiet --system ${USER} && echo " Done." || echo " Failed."
+        fi
+        if getent group ${GROUP} >/dev/null; then
+            echo -n "Removing group '${GROUP}'..."
+            delgroup --quiet --system --only-if-empty ${GROUP} && echo " Done." || echo " Failed."
+        fi
         ;;
 
     upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
