Use defaults from /etc/default/minidlna in {pre,post}{inst,rm}

diff --git a/debian/minidlna.preinst b/debian/minidlna.preinst
--- a/debian/minidlna.preinst
+++ b/debian/minidlna.preinst
@@ -3,9 +3,22 @@
 
 set -e
 
-USER=minidlna
-GROUP=${USER}
-HOMEDIR=/var/lib/minidlna
+unset USER
+
+DEFAULT=/etc/default/minidlna
+
+# Get values from ${DEFAULT}, if it exists.
+[ -r ${DEFAULT} ] && . ${DEFAULT}
+
+# Set the default user and group.
+if [ -z ${USER} ]; then
+    USER=minidlna
+fi
+if [ -z ${GROUP} ]; then
+    GROUP=minidlna
+fi
+
+HOME=/var/lib/minidlna
 
 # Based on the mediatomb debian package.
 
@@ -18,25 +31,39 @@ case "$1" in
             set +e
         fi
 
-        # Creating ${GROUP} if it isn't already there.
+        # Create ${GROUP} if it isn't already there. If ${GROUP} is different
+        # from the default value, assume it was properly configured already.
         if ! getent group ${GROUP} >/dev/null; then
-            # Adding system group.
-            addgroup --quiet --system ${GROUP}
+            if [ ${GROUP} = "minidlna" ]; then
+                # Adding system group.
+                addgroup --quiet --system ${GROUP}
+            else
+                echo "Error: Group \`${GROUP}' set in ${DEFAULT} does not" \
+                     "exist" >&2
+                exit 1
+            fi
         fi
 
-        # Creating ${USER} if it isn't already there.
+        # Create ${USER} if it isn't already there. If ${USER} is different
+        # from the default value, assume it was properly configured already.
         if ! getent passwd ${USER} >/dev/null; then
-            # Adding system user.
-            adduser \
-                --quiet \
-                --system \
-                --ingroup ${GROUP} \
-                --home "${HOMEDIR}" \
-                --gecos "MiniDLNA server" \
-                --shell /usr/sbin/nologin \
-                --disabled-login \
-                --disabled-password \
-                ${USER}
+            if [ ${USER} = "minidlna" ]; then
+                # Adding system user.
+                adduser \
+                    --quiet \
+                    --system \
+                    --ingroup ${GROUP} \
+                    --home "${HOME}" \
+                    --gecos "MiniDLNA server" \
+                    --shell /usr/sbin/nologin \
+                    --disabled-login \
+                    --disabled-password \
+                    ${USER}
+            else
+                echo "Error: User \`${USER}' set in ${DEFAULT} does not" \
+                     "exist" >&2
+                exit 1
+            fi
         fi
 
         # End of NIS tolerance zone.
